config/routes.rb
Rails.application.routes.draw do
  get '/tasks/my', to: 'tasks#users_tasks'
  get '/', to: 'main_views#show'
  get '/register', to: 'users#new'
  post 'tasks/assign/:id', to: 'tasks#assign'
  resources :users, :roles, :priorities, :tasks
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :priority
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :default_values
  belongs_to :role
  validates :login, uniqueness: true

  def password=(raw)
    self.password_digest = BCrypt::Password.create(raw)
  end

  def password
    self.password_digest
  end

  def is_password?(raw)
    BCrypt::Password.new(password_digest).is_password?(raw)
  end

  private
  def default_values
    self.role_id ||= 2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end
end

app/controllers/main_views_controller.rb
class MainViewsController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  def index
    @priorities = Priority.all
    render json: { result: 'Empty array' }, status: 200 if @priorities.empty?
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all
    render json: { result: 'Empty array' }, status: 200 if @roles.empty?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # Look up the user the database
    @user = User.find_by(login: user_params[:login])
    if @user && @user.is_password?(user_params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @user = User.new
      flash[:notice] = "Invalid email or password"
      redirect_to '/sign_in'
    end
    # Compare their password
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:login, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def update
    @task = Task.find_by(id: params[:id])
    if @task.update( title: params[:task][:title], body: params[:task][:body], priority_id: params[:task][:priority_id])
      redirect_to tasks_path
    else
      flash[:notice] = @task.errors.full_messages.to_sentence
      redirect_to edit_task_path
    end
  end

  def show
    @task = Task.find_by(id: params[:id])
  end

  def destroy
    @task = Task.find_by(id: params[:id])
    @task.destroy
    flash[:notice] = @task.errors.full_messages.to_sentence unless @task.destroy
    redirect_to tasks_path
  end

  def assign
    @task = Task.find_by(id: params[:id])
    if @task.update(assignee_id: session[:user_id])
      redirect_to tasks_path
    else
      flash[:notice] = @task.errors.full_messages.to_sentence unless @task.destroy
      redirect_to tasks_path
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.reporter_id ||= session[:user_id]
    if @task.save
      redirect_to tasks_path
    else
      flash[:notice] = @task.errors.full_messages.to_sentence
      redirect_to new_task_path
    end
  end

  def users_tasks
    @tasks = Task.all.where(assignee_id: session[:user_id])
  end

  def new
    @task = Task.new
  end

  private
  def task_params
    params.require(:task).permit(:title, :body, :priority_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:notice] = @user.errors.full_messages.to_sentence
      redirect_to '/register'
    end
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user
      new_user = user_from_params(params)
      User.update(new_user)
      render json: {result: 'update successful', user: new_user}
    else
      render json: {result: "Exception, no find user with id: #{params[:id]}", user: @user}
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
  end


  private
  def user_params
    params.require(:user).permit(:login, :password, :name, :surname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_views_helper.rb
module MainViewsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/main_views/show.html.erb
<%= render 'layouts/navbar' %>

app/views/priorities/index.html.erb
<h1>Priorities#index</h1>
<%@priorities.each do |priority| %>
  <h4>Role id: <%=priority.id%> </h4>
  <h4>Role name: <%=priority.title%> </h4>
<% end %>

app/views/roles/index.html.erb
<h1>Roles</h1>
<%@roles.each do |role| %>
  <h4>Role id: <%=role.id%> </h4>
  <h4>Role name: <%=role.title%> </h4>
<% end %>

app/views/tasks/_tasks.html.erb
<% @tasks.each do |task| %>
  <div style="margin: 40px;border-radius: 10px; padding: 10px; border: 4px solid black; width: 30vw; justify-content: space-between; display: flex">
    <div style="width: 50%">
      <p style="font-size: 18px; font-weight: bold"><%= task.title %></p>
      <p style="font-size: 16px; font-weight: bold">Reported by: <%= User.find_by(id: task.reporter_id).name %></p>
      <% if task.assignee_id %>
        <p style="font-size: 16px; font-weight: bold">Assigner: <%= User.find_by(id: task.assignee_id).name %></p>
      <% end %>
      <p style="max-width: 250px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><%= task.body %></p>
      <p style="font-size: 14px; font-weight: lighter">Priority: <%= Priority.find_by(id: task.priority_id).title %></p>
    </div>
    <div style="justify-content: left">
      <ul class="navbar-nav">
        <li class="nav-item" style="margin-right: 20px"><%= link_to "View", task_path(id: task.id) %></li>
        <% if task.reporter_id == session[:user_id] || User.find_by(id: session[:user_id]).role_id == 1 %>
          <li class="nav-item" style="margin-right: 20px"><%= link_to "Edit", edit_task_path(id: task.id) %></li>
          <li class="nav-item" style="margin-right: 20px"><%= button_to "Delete", "#{tasks_path}/#{task.id}", method: :delete %></li>
        <% end %>
        <% unless task.assignee_id %>
          <li class="nav-item" style="margin-right: 20px"><%= button_to "Assign to me", "#{tasks_path}/assign/#{task.id}", method: :post %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'layouts/navbar' %>
<% if notice %>
  <p class="alert alert-danger" id="notice"><%= notice %></p>
<%end %>
<div style="margin: 40px; width: 50%; justify-content: center">
  <%= form_with model: @task do |form| %>
    <p class="form-label" style="text-align: center"><%= form.label :title, 'Title' %></p>
    <p class="form-control"><%= form.text_field :title%></p>
    <p class="form-label" style="text-align: center"><%= form.label :body, 'Body' %></p>
    <p class="form-control"><%= form.text_area :body, rows: 5 %></p>
    <p class="form-label" style="text-align: center"><%= form.label :priority_id, 'Priority' %></p>
    <p class="form-control"><%= form.text_field :priority_id%></p>
    <div id="emailHelp" class="form-text">1 - Low; 2 - Medium; 3 - High</div>
    <p style="text-align: center"><%= form.submit 'Save' %></p>
  <% end %>
</div>

app/views/tasks/index.html.erb
<%= render 'layouts/navbar' %>
<% if current_user %>
  <% if notice %>
    <p class="alert alert-danger" id="notice"><%= notice %></p>
  <% end %>
  <div style="margin: 40px">
    <h1>Tasks</h1>
    <h4 style="margin-top: 20px"><%= link_to "Create new task", new_task_path %></h4>
  </div>

  <%= render 'tasks' %>
<% end %>

app/views/tasks/new.html.erb
<%= render 'layouts/navbar' %>
<% if notice %>
  <p class="alert alert-danger" id="notice"><%= notice %></p>
<%end %>
<form action="/tasks" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="container-md">
    <div class="mb-3">
      <label for="title" class="form-label">Title</label>
      <input type="text" name="task[title]" class="form-control" id="title" aria-describedby="emailHelp" value="<%= @task.title %>">
    </div>
    <div class="mb-3">
      <label for="body" class="form-label">Body</label>
      <input type="text" name="task[body]" class="form-control" id="body" aria-describedby="emailHelp" value="<%= @task.body %>">
    </div>
    <div class="mb-3">
      <label for="priority_id" class="form-label">Priority</label>
      <input type="number" name="task[priority_id]" class="form-control" id="priority_id" aria-describedby="emailHelp" value="<%= @task.priority_id %>">
      <div id="emailHelp" class="form-text">1 - Low; 2 - Medium; 3 - High</div>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </div>
</form>

app/views/tasks/show.html.erb
<%= render 'layouts/navbar' %>
<div style="margin: 40px">
  <h1>Title: <%= @task.title %></h1>
  <h3>Reported by: <%= User.find_by(id: @task.reporter_id).name %></h3>
  <% if User.find_by(id: @task.assignee_id) %>
    <h3>Assigner: <%= User.find_by(id: @task.assignee_id).name %></h3>
  <% end %>
  <h5>Body: <%= @task.body %></h5>
  <h5>Priority: <%= Priority.find_by(id: @task.priority_id).title %></h5>
</div>

app/views/tasks/users_tasks.html.erb
<%= render 'layouts/navbar' %>
<% if current_user %>
  <% if notice %>
    <p class="alert alert-danger" id="notice"><%= notice %></p>
  <% end %>
  <div style="margin: 40px">
    <h1>My issues</h1>
  </div>
<%= render 'tasks' %>
<% end %>

app/views/users/create.html.erb
Successful create!

app/views/users/new.html.erb
<%= render 'layouts/navbar' %>
<% if notice %>
  <p class="alert alert-danger" id="notice"><%= notice %></p>
<%end %>
<h1>Registration form</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="container-md">
    <div class="mb-3">
      <label for="login" class="form-label">Login</label>
      <input type="text" name="user[login]" class="form-control" id="login" aria-describedby="emailHelp" value="<%= @user.login %>">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">Name</label>
      <input type="text" name="user[name]" class="form-control" id="name" aria-describedby="emailHelp" value="<%= @user.name %>">
    </div>
    <div class="mb-3">
      <label for="surname" class="form-label">Surname</label>
      <input type="text" name="user[surname]" class="form-control" id="surname" aria-describedby="emailHelp" value="<%= @user.surname %>">
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" name="user[password]" class="form-control" id="password" aria-describedby="emailHelp" value="<%= @user.password %>">
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
  </div>
</form>

app/views/users/show.html.erb
<h1>Show</h1>